

Report 50044 "TimeSheet Individual Report"
{
	RDLCLayout = 'Layouts/TimeSheet Individual Report.rdlc'; DefaultLayout = RDLC;

	dataset
	{
		dataitem("TE Time Sheet1";"TE Time Sheet1")
		{
			RequestFilterFields = "Global Dimension 1 Code";
			column(ReportForNavId_1000000000; 1000000000) {} // Autogenerated by ForNav - Do not delete
			column(EmployeeNo; "TE Time Sheet1"."Employee No")
			{
			}
			column(DocumentNo_TETimeSheet1; "TE Time Sheet1"."Document No.")
			{
			}
			column(EmployeeName; "TE Time Sheet1"."Employee Name")
			{
			}
			column(Narration; "TE Time Sheet1".Narration)
			{
			}
			column(Date; "TE Time Sheet1".Date)
			{
			}
			column(Hours; "TE Time Sheet1".Hours)
			{
			}
			column(ProjectCode; "TE Time Sheet1"."Global Dimension 1 Code")
			{
			}
			column(ProjectName; "TE Time Sheet1".Description)
			{
			}
			column(Period; Period)
			{
			}
			column(LeaveType; "TE Time Sheet1"."Leave Type")
			{
			}
			column(Status_TETimeSheet; "TE Time Sheet1".Status)
			{
			}
			column(ApprovedBy; ApprovedBy)
			{
			}
			column(LastDate; LastDate)
			{
			}
			column(Signature; HREmployees.Signature)
			{
			}
			column(AsAt; AsAt)
			{
			}
			column(Picture; CompanyInfo.Picture)
			{
			}
			column(phone; CompanyInfo."Phone No.")
			{
			}
			column(Address; CompanyInfo.Address)
			{
			}
			column(Email; CompanyInfo."E-Mail")
			{
			}
			column(PostalCode; CompanyInfo."Post Code")
			{
			}
			column(Address2; CompanyInfo."Address 2")
			{
			}
		
			column(Name; CompanyInfo.Name)
			{
			}
			column(RequesterSign; TimesheetLines."Requester Signature")
			{
			}
			column(Approver1Sign; TimesheetLines.Approver1Signature)
			{
			}
			column(Approver2Sign; TimesheetLines.Approver2Signature)
			{
			}
			column(Approver1Name; Approver1Name)
			{
			}
			column(Approver2Name; Approver2Name)
			{
			}
			column(Approver2Date; Approver2Date)
			{
			}
			column(Approver1Date; Approver1Date)
			{
			}
			column(RequesterDate; RequesterDate)
			{
			}
			trigger OnAfterGetRecord();
			begin
				//"TE Time Sheet1".SETFILTER(Date,'%1..%2',CALCDATE('-CM',AsAt),CALCDATE('CM',AsAt));
				ApprovedBy:='';
				LastDate:=Date;
				 HREmployees.Reset;
				 HREmployees.SetRange(HREmployees."No.","TE Time Sheet1"."Employee No");
				 if HREmployees.FindFirst then begin
				  RequestName:=HREmployees.FullName;
				  HREmployees.CalcFields(HREmployees.Signature);
				  end;
				TimesheetLines.Reset;
				TimesheetLines.SetRange(Timesheetcode,"TE Time Sheet1"."Document No.");
				if TimesheetLines.FindSet then begin
				//IF TimesheetLines."Requester Signature".HASVALUE=FALSE THEN BEGIN
				  HREmployees.Reset;
				  HREmployees.SetRange("No.",TimesheetLines."Employee No");
				  if HREmployees.FindFirst then begin
				  HREmployees.CalcFields(Signature);
				  TimesheetLines."Requester Signature":= HREmployees.Signature;
					//END;
				  end;
				ApprovalEntry.Reset;
				  ApprovalEntry.SetRange("Document No.",TimesheetLines.Timesheetcode);
				  ApprovalEntry.SetRange("Sequence No.",1);
				  if ApprovalEntry.FindFirst then begin
					RequesterDate:=ApprovalEntry."Date-Time Sent for Approval";
					end;
				if Approver1Name='' then begin
				ApprovalEntry.Reset;
				ApprovalEntry.SetRange("Document No.",TimesheetLines.Timesheetcode);
				ApprovalEntry.SetRange("Sequence No.",1);
				ApprovalEntry.SetRange(Status,ApprovalEntry.Status::Approved);
				if ApprovalEntry.FindFirst then begin
				  HREmployees.Reset;
				  HREmployees.SetRange("User ID",ApprovalEntry."Approver ID");
				  if HREmployees.FindFirst then begin
				  HREmployees.CalcFields(Signature);
				  TimesheetLines.Approver1Signature:=HREmployees.Signature;
				  Approver1Name:=HREmployees.FullName;
				  Approver1Date:=ApprovalEntry."Last Date-Time Modified";
				  end;
				  end;
				  end;
				if Approver2Name='' then begin
				ApprovalEntry.Reset;
				ApprovalEntry.SetRange("Document No.",TimesheetLines.Timesheetcode);
				ApprovalEntry.SetRange("Sequence No.",2);
				ApprovalEntry.SetRange(Status,ApprovalEntry.Status::Approved);
				if ApprovalEntry.FindFirst then begin
				  HREmployees.Reset;
				  HREmployees.SetRange("User ID",ApprovalEntry."Approver ID");
				  if HREmployees.FindFirst then begin
				  HREmployees.CalcFields(Signature);
				  TimesheetLines.Approver2Signature:=HREmployees.Signature;
				  Approver2Name:=HREmployees.FullName;
				  Approver2Date:=ApprovalEntry."Last Date-Time Modified";
				  end;
				  end;
				  end;
				  end;
				  TimesheetLines.Modify;
			end;
			
		}
	}

	requestpage
	{

  
		SaveValues = false;	  layout
		{
			area(content)
			{
				group(Options)
				{
					Caption = 'Options';
				
				}
			}
		}

		actions
		{
		}
		trigger OnOpenPage()
		begin
		
		end;
	}

	trigger OnInitReport()
	begin
		CompanyInfo.Get();
		CompanyInfo.CalcFields(Picture);
	


	end;

	trigger OnPostReport()
	begin

	end;

	trigger OnPreReport()
	begin
		Period := "TE Time Sheet1".GetFilter("TE Time Sheet1".Date);
	
	end;
	var
		Period: Text;
		ApprovedBy: Text;
		Employee: Record Employee;
		HREmployees: Record "HR Employees";
		LastDate: Date;
		AsAt: Date;
		Name: Text;
		CompanyInfo: Record "Company Information";
		TimesheetLines: Record TimesheetLines;
		ApprovalEntry: Record "Approval Entry";
		RequesterDate: DateTime;
		Approver1Name: Text;
		Approver2Name: Text;
		Approver1Date: DateTime;
		Approver2Date: DateTime;
		RequestName: Text;


	
}
